#!/usr/bin/env bash

set -e

exec 3>&1 # make stdout available as fd 3 for the result
exec 1>&2 # redirect all output to stderr for logging

source=$1
if [ -z "$source" ]; then
  echo "usage: $0 <path/to/source>" >&2
  exit 1
fi

payload=$(mktemp /tmp/artifactory-deb.XXXXXX)
cat > "$payload" <&0

verbose_option() {
  local verbose=$(jq -r '.source.verbose // ""' < $payload)
  if [ "$verbose" = "true" ]; then
    echo "--verbose"
  fi
}

project_option() {
  local project=$(jq -r '.params.project // ""' < $payload)
  if [ -n "$project" ]; then
    echo "-p $project"
  fi
}

command_arguments() {
  local cmd=$1
  echo "$cmd $(${cmd}_command_options)"
}

down_command_rmi() {
  local rmi=$(jq -r '.params.options.rmi // ""' < $payload)
  if [ -n "$rmi" ]; then
    echo "--rmi $rmi"
  fi
}

down_command_volumes() {
  local volumes=$(jq -r '.params.options.volumes // ""' < $payload)
  if [ "$volumes" = "true" ]; then
    echo "--volumes"
  fi
}

down_command_options() {
  echo \
    $(down_command_rmi) \
    $(down_command_volumes) \
    $(command_opt_remove_orphans) \
    $(command_opt_timeout)
}

kill_command_opt_signal() {
  local signal=$(jq -r '.params.options.signal // ""' < $payload)
  if [ -n "$signal" ]; then
    echo "-s $signal"
  fi
}

kill_command_options() {
  echo \
    $(kill_command_opt_signal) \
    $(service_arguments)
}

restart_command_options() {
  echo \
    $(command_opt_timeout) \
    $(service_arguments)
}

start_command_options() {
  service_arguments
}

stop_command_options() {
  echo \
    $(command_opt_timeout) \
    $(service_arguments)
}

up_command_opt_no_deps() {
  local no_deps=$(jq -r '.params.options.no_deps // ""' < $payload)
  if [ "$no_deps" = "true" ]; then
    echo "--no-deps"
  fi
}

up_command_opt_force_recreate() {
  local force_recreate=$(jq -r '.params.options.force_recreate // ""' < $payload)
  if [ "$force_recreate" = "true" ]; then
    echo "--force-recreate"
  fi
}

up_command_opt_no_recreate() {
  local no_recreate=$(jq -r '.params.options.no_recreate // ""' < $payload)
  if [ "$no_recreate" = "true" ]; then
    echo "--no-recreate"
  fi
}

up_command_renew_anon_volumes() {
  local renew=$(jq -r '.params.options.renew_anon_volumes // ""' < $payload)
  if [ "$renew" = "true" ]; then
    echo "--renew-anon-volumes"
  fi
}

command_opt_remove_orphans() {
  local remove_orphans=$(jq -r '.params.options.remove_orphans // ""' < $payload)
  if [ "$remove_orphans" = "true" ]; then
    echo "--remove-orphans"
  fi
}

command_opt_timeout() {
  local timeout=$(jq -r '.params.options.timeout // ""' < $payload)
  if [ -n "$timeout" ]; then
    echo "--timeout $timeout"
  fi
}

up_command_scale() {
  local scale=$(jq -r '.params.options.scale // {}' < $payload)
  IFS=$'\n'
  for entry in $(echo "$scale" | jq -r 'to_entries[] | [.key, .value] | @tsv'); do
    local service=$(echo $entry | awk '{print $1}')
    local val=$(echo $entry | awk '{print $2}')
    echo -e "--scale $service=$val "
  done
  unset IFS
}

up_command_options() {
  echo \
    -d \
    --no-build \
    $(up_command_opt_no_deps) \
    $(up_command_opt_force_recreate) \
    $(up_command_opt_no_recreate) \
    $(up_command_renew_anon_volumes) \
    $(command_opt_remove_orphans) \
    $(up_command_scale) \
    $(command_opt_timeout) \
    $(service_arguments)
}

service_arguments() {
  local services=$(jq -r '.params.services // [] | join(" ")' < $payload)
  echo "$services"
}

log_into_registries() {
  local registries=$(jq -r '.source.registries // []' < $payload)
  IFS=$'\n'
  for entry in $(echo "$registries" | jq -rc '.[]'); do
    local host=$(echo "$entry" | jq -r '.host // ""')
    local username=$(echo "$entry" | jq -r '.username // ""')
    local password=$(echo "$entry" | jq -r '.password // ""')

    echo "Logging into registry: $host"
    echo "$password" | docker login -u "$username" --password-stdin "$host"
  done
  unset IFS
}

# lifted from https://github.com/concourse/docker-image-resource/blob/master/assets/common.sh
configure_ca_certs() {
  local raw_ca_certs=$(jq -r '.source.ca_certs // []' < $payload)
  local cert_count="$(echo "$raw_ca_certs" | jq -r '. | length')"

  for i in $(seq 0 $(expr "$cert_count" - 1));
  do
    local cert_dir="/etc/docker/certs.d/$(echo $raw_ca_certs | jq -r .[$i].domain)"
    mkdir -p "$cert_dir"
    echo "$raw_ca_certs" | jq -r ".[$i].cert" >> "${cert_dir}/ca.crt"
  done
}

write_env_file() {
  local env_entries=$(jq -r '.params.env // ""' < $payload)
  local env_file=$(jq -r '.params.env_file // ""' < $payload)

  if [ -n "$env_entries" ]; then
    echo -n '' > .env

    IFS=$'\n'
    for entry in $(echo "$env_entries" | jq -r 'to_entries[] | [.key, .value] | @tsv'); do
      local key=$(echo $entry | awk '{print $1}')
      local val=$(echo $entry | awk '{print $2}')
      echo "$key=$val" >> .env
    done
    unset IFS
  elif [ -n "$env_file" ]; then
    cp "$source/$env_file" .env
  fi
}

validate_command() {
  local cmd=$1
  case $cmd in
  down) ;;
  kill) ;;
  restart) ;;
  start) ;;
  stop) ;;
  up) ;;
  *)
    echo "Unsupported command: $cmd" >&2
    echo "Possible commands: down, kill, restart, start, stop, up" >&2
    exit 1
  esac
}

tlsverify() {
  local tls=$(jq -r '.source.tlsverify // ""' < $payload)
  [ -z "$tls" ] && return
  local client_home="$HOME/.docker"
  mkdir -p "$client_home"
  
  for key in ca cert key; do
    local value=$(jq -r ".source.tlsverify.${key}" < $payload)
    [ -z "$value" ] && echo "ERROR: 'source.tlsverify.$key' must be defined" && exit 1
    echo "$value" > "${client_home}/${key}.pem"
  done

  echo -n "--tlsverify "
}

resolve_docker_host() {
  # Check host param
  local host=$(jq -r '.params.host // ""' < $payload)
  [[ -n $host ]] && { echo "$host"; return; }

  # Check host_file param
  local host_file=$(jq -r '.params.host_file // ""' < $payload)
  if [[ -n $host_file ]]; then
    # Extract host line from host file
    local host_index=$(jq -r '.params.host_index // "1"' < $payload)
    host=$(sed -n "${host_index}p" "$host_file")
    [[ -n $host ]] && { echo "$host"; return; }
  fi

  # Check host source attribute
  host=$(jq -r '.source.host // ""' < $payload)
  [[ -n $host ]] && { echo "$host"; return; }

  # Uh oh
  echo 'a docker host must be defined' >&2
  exit 1
}

host=$(resolve_docker_host)
port=$(jq -r '.source.port // "2376"' < $payload)
export DOCKER_HOST="${host}:${port}"

compose_file=$(jq -r '.params.compose_file // "docker-compose.yml"' < $payload)
path=$(jq -r '.params.path // "."' < $payload)
print=$(jq -r '.params.print // false' < $payload)
wait_before=$(jq -r '.params.wait_before // ""' < $payload)
wait_after=$(jq -r '.params.wait_after // ""' < $payload)
command=$(jq -r '.params.command // "up"' < $payload)
pull=$(jq -r '.params.pull // "false"' < $payload)
validate_command "$command"

cd $source/$path

docker-compose -v

configure_ca_certs
log_into_registries
write_env_file

if [ "$print" = "true" ]; then
  echo "${compose_file}:"
  cat "$compose_file"
fi

if [ -n "$wait_before" ]; then
  echo "Waiting $wait_before seconds..."
  sleep "$wait_before"
fi

if [ "$pull" == "true" ]; then
  docker-compose \
    -f "$compose_file" \
    pull \
    --include-deps
fi

docker-compose \
  --no-ansi \
  -f "$compose_file" \
  $(tlsverify) \
  $(verbose_option) \
  $(project_option) \
  $(command_arguments $command);

if [ -n "$wait_after" ]; then
  echo "Waiting $wait_after seconds..."
  sleep "$wait_after"
fi

jq -n "{
  version: {
    digest: $((echo -n "sha256:"; sha256sum "$compose_file") | cut -d ' ' -f1 | jq -R .)
  }
}" >&3
